### ISSUE TITLE
Guiceyfruit 2.0 does not seem to work with Guice 3.0

### ISSUE THREAD

**Issue by GoogleCodeExporter** [bufan1228/guiceyfruit#38]
```
Injectors.close(injector) throws this error:

Caused by: java.lang.NoClassDefFoundError: 
com/google/inject/internal/MatcherAndConverter
    at org.guiceyfruit.support.internal.Errors.<clinit>(Errors.java:442)
    at org.guiceyfruit.support.internal.CloseErrorsImpl.<init>(CloseErrorsImpl.java:33)
    at org.guiceyfruit.Injectors.close(Injectors.java:302)
```

Original issue reported on code.google.com by `ashwin.j...@gmail.com` on 23 Aug 2011 at 12:26

**Comment by GoogleCodeExporter** [comment]
```
I see the same issue
```

Original comment by `vtks...@gmail.com` on 2 Feb 2012 at 7:06
